repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: ["--config-file=backend/pyproject.toml"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@4.0.0-alpha.8
          - prettier-plugin-svelte@latest

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.30.1
    hooks:
      - id: eslint
        args: ["--config=frontend/eslint.config.js", "--fix", "frontend/"]
        files: "^frontend/.*\\.(ts|js|svelte)$"
        additional_dependencies:
          - "eslint@9.30.1"
          - "eslint-plugin-svelte@latest"
          - "svelte-eslint-parser@latest"
