category: "アクティビティ"
questions:
  - "国内旅行派？海外旅行派？"
  - "一人旅派？友達と旅行派？"
  - "旅行は計画的？自由？"
  - "遊び行くなら山？海？都市部？"
  - "今まで行った中で一番良かった場所は？"
  - "次に行ってみたい場所は？"
  - "旅行で一番重視することは？"
  - "旅行先での楽しみ方は？"
  - "いつも買うお土産は？"
  - "好きな食べ物のジャンルは？"
  - "和食、洋食、中華の中で、一番好きなのは？"
  - "辛い料理は好き？"
  - "甘いもの派？しょっぱいもの派？"
  - "料理を作るのは好き？もし作るなら、得意料理は何？"
  - "外食派？家食派？"
  - "新しい料理に挑戦するのは好き？"
  - "食べ歩きは好き？"
  - "好きな飲み物は？"
  - "食事で一番大切にすることは？"
  - "好きなアウトドア活動は？"
  - "キャンプやBBQは好き？"
  - "ハイキングや登山は好き？"
  - "海や川で遊ぶなら、どんなアクティビティが好き？"
  - "好きなウィンタースポーツは？"
  - "スポーツ観戦は好き？"
  - "フェスやコンサートは好き？"
  - "美術館や博物館は好き？"
  - "ショッピングではどんなものを買うのが好き？"
  - "好きなテーマパークは？"
  - "旅先でのハプニング、どう楽しむタイプ？"
  - "旅行のパッキング、得意？苦手？こだわりある？"
  - "旅行の思い出、写真派？それとも心に刻む派？"
  - "初めての飲食店では、冒険して新しいもの挑戦派？定番メニューで安心派？"
  - "食のこだわり、これだけは譲れない！ってある？"
  - "料理、作るならどんな時に、誰のために作る？"
  - "休日の朝、何して過ごすのが好き？"
  - "ストレス解消、どんなアクティビティで発散する？"
  - "新しい趣味を始めるなら、何に挑戦したい？"
  - "最近ハマってることは？"
  - "最後の晩餐に何食べたい？"
