category: "アクティビティ"
questions:
  - "好きな旅行スタイルは？"
  - "国内旅行？海外旅行？"
  - "一人旅？友達との旅行？"
  - "計画的な旅行？自由な旅行？"
  - "山？海？都市部？"
  - "今まで行った中で一番良かった場所は？"
  - "次に行ってみたい場所は？"
  - "旅行で一番重視することは？"
  - "旅行先での楽しみ方は？"
  - "お土産は買う派？"
  - "好きな食べ物のジャンルは？"
  - "和食？洋食？中華？その他？"
  - "辛い料理は好き？"
  - "甘いもの？しょっぱいもの？"
  - "料理は作る？"
  - "外食？家食？"
  - "新しい料理に挑戦するのは好き？"
  - "食べ歩きは好き？"
  - "好きな飲み物は？"
  - "食事で一番大切にすることは？"
  - "アウトドア活動は好き？"
  - "キャンプやBBQは好き？"
  - "ハイキングや登山は好き？"
  - "海や川でのアクティビティは好き？"
  - "ウィンタースポーツは好き？"
  - "スポーツ観戦は好き？"
  - "フェスやコンサートは好き？"
  - "美術館や博物館は好き？"
  - "ショッピングは好き？"
  - "テーマパークは好き？"
