category: values
title: "働き方とキャリアに関する30の質問"
description: "仕事に対する価値観や理想の働き方について知る質問集"
questions:
  - "理想の働き方は？"
  - "仕事で最も重視することは？"
  - "チームワークで大切なことは？"
  - "リーダーシップで意識することは？"
  - "スキルアップで興味がある分野は？"
  - "効率重視？丁寧さ重視？"
  - "スピード重視？品質重視？"
  - "個人作業？チーム作業？"
  - "ルーティンワーク？変化のある仕事？"
  - "専門性を深める？幅広いスキルを身につける？"
  - "安定？挑戦？"
  - "大企業？中小企業？"
  - "リモートワーク？オフィスワーク？"
  - "フレックス？固定時間？"
  - "長期プロジェクト？短期プロジェクト？"
  - "クリエイティブ？ロジカル？"
  - "人と関わる？一人で集中？"
  - "ゼロから作る？改善・改良する？"
  - "計画を立てる？実行する？"
  - "分析する？直感で判断する？"
  - "教える？学ぶ？"
  - "サポートする？リードする？"
  - "安全性重視？革新性重視？"
  - "プロセス重視？結果重視？"
  - "短期成果？長期的な影響？"
  - "競争？協力？"
  - "専門分野？総合的？"
  - "理論？実践？"
  - "国内？グローバル？"
  - "仕事を通じて実現したい理想は？"
