category: "キャリア"
questions:
  - "理想の働き方は？"
  - "仕事で最も重視することは？"
  - "チームワークで大切にしていることは？"
  - "リーダーシップで意識することは？"
  - "スキルアップで興味がある分野は？"
  - "仕事は効率重視派？丁寧じっくり派？"
  - "個人作業派？チーム作業派？"
  - "ルーティンワーク派？変化のある仕事派？"
  - "専門性を深める派？幅広いスキルを身につける派？"
  - "仕事の姿勢は安定派？挑戦派？"
  - "大企業派？ベンチャー企業派？"
  - "リモートワーク派？オフィスワーク派？"
  - "クリエイティブなタイプ？ロジカルなタイプ？"
  - "人と関わる仕事派？一人で集中する仕事派？"
  - "ゼロから作る仕事派？改善・改良する仕事派？"
  - "計画を立てる仕事派？実行する仕事派？"
  - "分析派？直感で判断派？"
  - "教える側？学ぶ側？"
  - "サポート役？リード役？"
  - "安全性を重視する派？革新性を重視する派？"
  - "プロセス重視派？結果重視派？"
  - "短期成果を求める派？長期的な影響を重視する派？"
  - "仕事では競争派？協力派？"
  - "専門分野を深める派？総合的なスキルを身につける派？"
  - "理論派？実践派？"
  - "国内志向？グローバル志向？"
  - "仕事を通じて実現したい理想は？"
  - "仕事で一番テンション上がる瞬間ってどんな時？"
  - "仕事で失敗しちゃったら、どう立ち直る？"
  - "理想の上司ってどんな人？"
  - "仕事とプライベート、どう切り替えてる？"
  - "キャリアで一番大切にしたいことって何？"
  - "新しいスキル、どうやって身につけるタイプ？"
  - "チームで働く時、自分の役割ってどんな感じ？"
