category: "子供時代"
questions:
  - "子供の頃の夢は？"
  - "一番好きだった遊びは？"
  - "好きだったおもちゃは？"
  - "よく見ていたアニメやテレビ番組は？"
  - "好きだった絵本や児童書は？"
  - "習い事はしていた？"
  - "運動は得意だった？"
  - "勉強は好きだった？"
  - "友達は多かった？"
  - "どんな性格の子だった？"
  - "家族との思い出で印象的なことは？"
  - "夏休みの過ごし方は？"
  - "好きだった給食のメニューは？"
  - "苦手だった食べ物は？"
  - "よく行った場所は？"
  - "誕生日やクリスマスの思い出は？"
  - "ペットを飼っていた？"
  - "怖かったものは？"
  - "憧れていた職業は？"
  - "よく遊んでいた場所は？"
  - "兄弟姉妹との関係は？"
  - "おじいちゃん・おばあちゃんとの思い出は？"
  - "子供の頃のヒーローは？"
  - "よく歌っていた歌は？"
  - "子供の頃の自分に一言かけるとしたら？"
