category: otaku
title: "創作と表現に関する30の質問"
description: "創作活動や自己表現について詳しく知る質問集"
questions:
  - "創作活動はする？"
  - "どんな形で自分を表現するのが好き？"
  - "インスピレーションを得る瞬間は？"
  - "創作意欲が湧く環境は？"
  - "完成させる？途中で満足する？"
  - "オリジナル？二次創作？"
  - "一人で創作？協力して創作？"
  - "計画的に創作？直感的に創作？"
  - "完璧主義？とりあえず形にする？"
  - "他の人に見せる？自分だけで楽しむ？"
  - "フィードバックを求める？自分の感覚を信じる？"
  - "トレンドを意識する？自分らしさを重視する？"
  - "技術向上を重視する？表現したいことを重視する？"
  - "長編？短編？"
  - "シリアス？コメディ？"
  - "リアル？ファンタジー？"
  - "ストーリー重視？ビジュアル重視？"
  - "キャラクター重視？世界観重視？"
  - "メッセージ性重視？エンターテイメント重視？"
  - "感情表現重視？技術表現重視？"
  - "革新的？古典的？"
  - "シンプル？複雑？"
  - "明るい？暗い？"
  - "希望的？現実的？"
  - "個人的？普遍的？"
  - "静的？動的？"
  - "繊細？大胆？"
  - "抽象的？具体的？"
  - "創作を通じて伝えたいことは？"
  - "創作活動で得られる一番の喜びは？"
