category: "エンタメ"
questions:
  - "創作活動はする？"
  - "どんな形で自分を表現するのが好き？"
  - "インスピレーションを得る瞬間は？"
  - "創作意欲が湧く環境は？"
  - "作品は最後まで作り上げる派？途中で満足しちゃう派？"
  - "オリジナル作品を作る派？二次創作を楽しむ派？"
  - "一人で集中して創作派？みんなで協力して創作派？"
  - "きちんと計画して創作派？直感でパッと創作派？"
  - "細部までこだわる完璧主義派？とりあえず形にする派？"
  - "作品は他の人にも見せたい派？自分だけでこっそり楽しむ派？"
  - "他の人の意見を聞きたい派？自分の感覚を信じる派？"
  - "トレンドを意識する？自分らしさを重視する？"
  - "技術向上を重視する？表現したいことを重視する？"
  - "長編？短編？"
  - "シリアスな作品派？コメディな作品派？"
  - "リアルな作品派？ファンタジーな作品派？"
  - "創作を通じて伝えたいことは何？"
  - "創作活動で一番の喜びは何？"
  - "何かを「生み出す」って、あなたにとってどんな意味？"
  - "アイデアがひらめく瞬間はどんな時？"
  - "創作で一番楽しい瞬間はいつ？"
  - "完成した作品、誰に一番最初に見せたい？"
