category: "エンタメ"
questions:
  - "映画館派？家で鑑賞派？"
  - "字幕派？吹き替え派？"
  - "邦画派？洋画派？"
  - "最新作派？名作派？"
  - "アクション？ドラマ？コメディ？ホラー？"
  - "一人で見る？みんなで見る？"
  - "集中して見る？ながら見？"
  - "レビューを読む？先入観なしで見る？"
  - "予告編を見る？見ない？"
  - "続編ものが好き？単発ものが好き？"
  - "音楽はどこで聴く？"
  - "プレイリスト派？アルバム通し派？"
  - "新しい音楽を探す？お気に入りをリピート？"
  - "歌詞重視？メロディ重視？"
  - "ライブに行く？音源で楽しむ？"
  - "邦楽？洋楽？"
  - "メジャー？インディーズ？"
  - "ソロアーティスト？バンド？"
  - "アップテンポ？バラード？"
  - "懐かしい曲？最新の曲？"
  - "ゲームはどのプラットフォームでするのが好き？"
  - "一人でプレイ？みんなでプレイ？"
  - "ストーリー重視？システム重視？"
  - "RPG？アクション？パズル？シミュレーション？"
  - "じっくりやり込む？サクッとクリア？"
  - "オンライン？オフライン？"
  - "攻略情報を見る？自力で進める？"
  - "コンプリートする？メインだけクリア？"
  - "新作ゲーム派？レトロゲーム派？"
  - "和ゲー派？洋ゲー派？"
  - "本は紙派？電子書籍派？"
  - "小説？ノンフィクション？"
  - "長編作品派？短編作品派？"
  - "シリーズもの派？単発もの派？"
  - "日本の作家派？海外の作家派？"
  - "古典作品派？現代作品派？"
  - "ベストセラー派？隠れた名作派？"
  - "じっくり読む？速読する？"
  - "静かな場所？適度に音がある場所？"
  - "エンタメを楽しむ上で最も大切にしていることは？"
  - "最近、心を揺さぶられたエンタメ作品ある？"
  - "もし自分が映画の主人公なら、どんなジャンルの物語がいい？"
  - "音楽を聴く時、どんな気分になりたい？"
  - "ゲームで一番「熱中した！」ってエピソードある？"
  - "本を読む時、どんな世界に没頭したい？"
  - "エンタメって、あなたにとってどんな存在？"
