category: otaku
title: "エンタメ好きのための40の質問"
description: "映画、音楽、ゲーム、書籍など幅広いエンタメについて"
questions:
  - "映画館派？家で鑑賞派？"
  - "字幕派？吹き替え派？"
  - "邦画派？洋画派？"
  - "最新作？名作？"
  - "アクション？ドラマ？コメディ？ホラー？"
  - "一人で見る？みんなで見る？"
  - "集中して見る？ながら見？"
  - "レビューを読む？先入観なしで見る？"
  - "予告編を見る？見ない？"
  - "続編がある？単発？"
  - "音楽はどこで聴く？"
  - "プレイリスト派？アルバム通し派？"
  - "新しい音楽を探す？お気に入りをリピート？"
  - "歌詞重視？メロディ重視？"
  - "ライブに行く？音源で楽しむ？"
  - "邦楽？洋楽？"
  - "メジャー？インディーズ？"
  - "ソロアーティスト？バンド？"
  - "アップテンポ？バラード？"
  - "懐かしい曲？最新の曲？"
  - "ゲームはどのプラットフォームで？"
  - "一人でプレイ？みんなでプレイ？"
  - "ストーリー重視？システム重視？"
  - "RPG？アクション？パズル？シミュレーション？"
  - "じっくりやり込む？サクッとクリア？"
  - "オンライン？オフライン？"
  - "攻略情報を見る？自力で進める？"
  - "コンプリートする？メインだけクリア？"
  - "新作？レトロゲーム？"
  - "和ゲー？洋ゲー？"
  - "本は紙派？電子書籍派？"
  - "小説？ノンフィクション？"
  - "長編？短編？"
  - "シリーズもの？単発？"
  - "日本の作家？海外の作家？"
  - "古典？現代？"
  - "ベストセラー？隠れた名作？"
  - "じっくり読む？速読する？"
  - "静かな場所？適度に音がある場所？"
  - "エンタメを楽しむ上で最も大切にしていることは？"
