category: "もしも"
questions:
  - "もし1つだけ願いが叶うなら？"
  - "もし透明人間になれたら何をする？"
  - "もし時間を止められるなら何をする？"
  - "もし過去に戻れるなら、いつに戻りたい？"
  - "もし未来を見ることができるなら、何を見たい？"
  - "もし宝くじで1億円当たったら？"
  - "もし無人島に1つだけ持って行けるとしたら？"
  - "もし好きな人と24時間過ごせるなら？"
  - "もし世界中どこでも瞬間移動できるなら？"
  - "もし動物と話せるようになったら？"
  - "もし空を飛べるようになったら？"
  - "もし死なない体になったら？"
  - "もし他人の心が読めるようになったら？"
  - "もし魔法が使えるようになったら？"
  - "もし自分がアニメのキャラクターになれるなら？"
  - "もし歴史上の人物と会えるなら誰と？"
  - "もし異世界に転生するとしたら？"
  - "もし世界が終わるまであと1日だとしたら？"
  - "もし自分の人生を映画にするとしたら？"
  - "もし子供の頃の自分に会えるなら？"
  - "もし理想の自分になれるとしたら？"
  - "もし世界中の人と友達になれるとしたら？"
  - "もし好きなゲームの世界に入れるとしたら？"
  - "もし自分だけの国を作れるとしたら？"
  - "もし時間が無限にあるとしたら何をする？"
  - "もし人生をやり直せるなら、どこからやり直したい？"
  - "もし一日だけ、誰か別の人になれるとしたら、誰になって何をする？"
  - "もし世界に一つだけ、新しいルールを作れるとしたら、どんなルールにする？"
  - "もし自分の人生のBGMを選ぶとしたら、どんな曲？"
  - "もしタイムスリップして旅に出るなら、いつのどこに行きたい？"
  - "もし自分の作品が世界中の人に届くとしたら、何を伝えたい？"
  - "もし世界を変えられるなら、何を変えたい？"
