category: "目標"
questions:
  - "新しいことを学ぶ時のモチベーションは？"
  - "効果的な学習方法は？"
  - "集中力を維持するコツは？"
  - "記憶に残りやすい学び方は？"
  - "理論派？実践派？"
  - "一人で学ぶ？みんなで学ぶ？"
  - "体系的に学ぶ？興味の赴くままに学ぶ？"
  - "深く学ぶ？広く学ぶ？"
  - "本で学ぶ？動画で学ぶ？体験で学ぶ？"
  - "すぐに活用する？じっくり理解してから活用する？"
  - "完璧に理解してから進む？とりあえず進んでみる？"
  - "ノートを取る派？頭で記憶する派？"
  - "復習を重視する？新しいことを重視する？"
  - "基礎を固める？応用から入る？"
  - "先生から学ぶ？独学する？"
  - "計画的に学ぶ？直感的に学ぶ？"
  - "競争を意識する？自分のペースを重視する？"
  - "結果を重視する？過程を重視する？"
  - "短期集中？長期継続？"
  - "朝学習？夜学習？"
  - "静かな環境？適度な雑音がある環境？"
  - "デジタル？アナログ？"
  - "質問することを重視する？自分で考えることを重視する？"
  - "失敗を恐れる？失敗から学ぶことを重視する？"
  - "学んだことをどう活かしたい？"
