category: "ライフスタイル"
questions:
  - "理想の1日のスケジュールは？"
  - "朝のルーティンで大切にしていることは？"
  - "夜のリラックス方法は？"
  - "週末の過ごし方のパターンは？"
  - "家での快適な過ごし方は？"
  - "外出時のお気に入りスポットのタイプは？"
  - "食事で大切にしていることは？"
  - "健康管理で意識していることは？"
  - "睡眠で気をつけていることは？"
  - "運動習慣はある？"
  - "ストレッチやリラクゼーションの習慣は？"
  - "デジタルデトックスを意識する？"
  - "情報収集の方法は？"
  - "SNSとの付き合い方は？"
  - "買い物をする時の基準は？"
  - "部屋の整理整頓のコツは？"
  - "季節の変わり目で楽しみにしていることは？"
  - "年中行事で大切にしているものは？"
  - "プレゼント選びで重視することは？"
  - "記念日の過ごし方は？"
  - "写真を撮る頻度は？"
  - "日記や記録をつける習慣は？"
  - "新しい場所を探検するのは好き？"
  - "地元愛はある？"
  - "旅行スタイルは？（計画派？自由派？）"
  - "お気に入りの移動手段は？"
  - "天気によって気分は変わる？"
  - "季節感を感じる瞬間は？"
  - "小さな贅沢はどんなもの？"
  - "自分にとってのご褒美は？"
