category: "エンタメ"
questions:
  - "好きなアニメのジャンルは？"
  - "漫画を読む時のこだわりは？"
  - "推し活の楽しみ方は？"
  - "ゲームで好きなジャンルは？"
  - "創作活動で興味があるものは？"
  - "好きなYouTubeのジャンルは？"
  - "音楽を聴くお気に入りのシチュエーションは？"
  - "映画の好みは？"
  - "スポーツで好きなものは？"
  - "コレクションしているものは？"
  - "趣味に使う時間はどのくらい？"
  - "趣味を始めたきっかけは？"
  - "趣味仲間との交流方法は？"
  - "新しい趣味を見つける方法は？"
  - "趣味にかける情熱の源は？"
  - "好きな作品の魅力を語るなら？"
  - "創作するか鑑賞するか、どちら派？"
  - "一人で楽しむか、みんなで楽しむか？"
  - "深く掘り下げるか、広く浅くか？"
  - "オンラインかオフラインか、どちらで楽しむ？"
  - "トレンドを追うか、マイペースか？"
  - "完璧主義か、楽しければOKか？"
  - "ストーリー重視か、キャラクター重視か？"
  - "ゲームは美しいグラフィック重視？面白いシステム重視？"
  - "王道作品派？マイナー作品派？"
  - "シリーズで長く楽しむ派？1作品で完結する方が好き？"
  - "リアルタイムでみんなと盛り上がる派？まとめて一気見する派？"
  - "原作で楽しむ派？アニメや映像で楽しむ派？"
  - "公式作品派？二次創作も楽しむ派？"
  - "新作か、名作か？"
  - "国内作品か、海外作品か？"
  - "メジャーか、インディーズか？"
  - "じっくり長編派？サクッと短編派？"
  - "ハッピーエンド派？ビターエンドも良い派？"
  - "笑えるコメディ派？深刻なシリアス派？"
  - "夢とファンタジー派？現実的な作品派？"
  - "ハラハラアクション派？まったり日常系派？"
  - "恋愛要素があった方が好き？なくても全然OK？"
  - "キャラクターの成長を見たい派？最初から完成されたキャラが好き？"
  - "考察したくなる複雑な作品派？シンプルで分かりやすい作品派？"
  - "作品は深く考察して楽しむ派？素直に楽しむ派？"
  - "話題の作品をチェックする派？自分の好みを大事にする派？"
  - "趣味を通じて得られた一番の収穫は？"
  - "あなたの「推し」への愛、どう表現してる？"
  - "もし好きな作品の世界に入れたら、何したい？"
  - "初めて「沼にハマった」作品って何？"
  - "この作品のここがすごい！って熱く語れるポイントある？"
  - "もし自分がキャラクターをデザインするなら、どんなキャラを作りたい？"
