category: "性格・特徴"
questions:
  - "自分の性格を一言で表すと？"
  - "周りの人からどんな人だと言われる？"
  - "自分の長所は？"
  - "自分の短所は？"
  - "インドア派？アウトドア派？"
  - "積極的？消極的？"
  - "楽観的？悲観的？"
  - "理想主義者？現実主義者？"
  - "感情的？論理的？"
  - "慎重派？行動派？"
  - "リーダータイプ？フォロワータイプ？"
  - "人見知りする？初対面でも話しやすい？"
  - "計画を立てる？その場の流れに任せる？"
  - "完璧主義？適当主義？"
  - "変化を求める？安定を求める？"
  - "競争が好き？協力が好き？"
  - "一人の時間が好き？人といる時間が好き？"
  - "新しいことに挑戦するのが好き？慣れたことを続けるのが好き？"
  - "自分の決断力はどう？"
  - "ストレス解消法は？"
  - "落ち込んだ時の立ち直り方は？"
  - "怒った時の対処法は？"
  - "嬉しい時の表現方法は？"
  - "集中力はある方？"
  - "記憶力はいい方？"
  - "創造力はある方？"
  - "観察力はある方？"
  - "直感力はある方？"
  - "自分らしさとは何？"
  - "自分の個性で誇れることは？"
  - "あなたの「ここが変！」って言われるところ、ある？"
  - "動物に例えるなら、自分は何の動物？"
  - "人生で一番「成長したな」って感じる瞬間は？"
  - "初対面の人と話す時、どんなことを意識してる？"
  - "あなたの「スイッチが入る」瞬間ってどんな時？"
