category: "人間関係"
questions:
  - "理想的な友人関係とは？"
  - "信頼できる人の特徴は？"
  - "良好な関係を築くために心がけていることは？"
  - "意見が合わない時の対処法は？"
  - "相手の気持ちを理解するために意識することは？"
  - "自分の気持ちを伝える時のコツは？"
  - "聞き上手？話し上手？"
  - "グループの中での自分の役割は？"
  - "リーダータイプ？サポータータイプ？"
  - "積極的にコミュニケーションを取る？待つタイプ？"
  - "大勢の中にいる？少数精鋭？"
  - "深い関係？広い関係？"
  - "安定した関係？刺激的な関係？"
  - "似た価値観の人？違う価値観の人？"
  - "同世代？年上？年下？"
  - "オンライン？オフライン？"
  - "仕事関係？プライベート関係？"
  - "地元の人？様々な地域の人？"
  - "同じ趣味の人？違う趣味の人？"
  - "感情を共有する？論理的に話し合う？"
  - "アドバイスを求める？話を聞いてもらう？"
  - "計画を一緒に立てる？自然体で付き合う？"
  - "お互いを高め合う？リラックスできる？"
  - "新しい発見がある？安心できる？"
  - "刺激的な会話？穏やかな会話？"
  - "真面目な話？楽しい話？"
  - "将来の話？今の話？"
  - "個人的な話？一般的な話？"
  - "問題解決型？共感型？"
  - "建設的な議論？和やかな雑談？"
  - "挑戦的な話題？安全な話題？"
  - "新しい視点？共通の視点？"
  - "質問する？答える？"
  - "教える？教わる？"
  - "人間関係で最も大切にしていることは？"
