category: "人間関係"
questions:
  - "理想的な友人関係とは？"
  - "信頼できる人の特徴は？"
  - "良好な関係を築くために心がけていることは？"
  - "意見が合わない時の対処法は？"
  - "相手の気持ちを理解するために意識することは？"
  - "自分の気持ちを伝える時のコツは？"
  - "聞き上手？話し上手？"
  - "グループの中での自分の役割は？"
  - "リーダータイプ？サポータータイプ？"
  - "積極的にコミュニケーションを取る？待つタイプ？"
  - "大勢の中にいるのが好き？少数精鋭が好き？"
  - "深い関係を築く派？幅広い関係を築く派？"
  - "安定した関係派？刺激的な関係派？"
  - "似た価値観の人が好き？違う価値観の人が好き？"
  - "同世代の人が好き？年上の人が好き？年下の人が好き？"
  - "オンラインでの交流派？オフラインでの交流派？"
  - "仕事関係の人と付き合うのが好き？プライベートでの関係が好き？"
  - "地元の人との付き合いが好き？様々な地域の人との付き合いが好き？"
  - "同じ趣味の人と付き合うのが好き？違う趣味の人と付き合うのが好き？"
  - "感情を共有する？論理的に話し合う？"
  - "アドバイスを求める？話を聞いてもらう？"
  - "計画を一緒に立てる？自然体で付き合う？"
  - "お互いを高め合う？リラックスできる？"
  - "新しい発見がある？安心できる？"
  - "刺激的な会話？穏やかな会話？"
  - "真面目な話？楽しい話？"
  - "将来の話？今の話？"
  - "個人的な話？一般的な話？"
  - "問題解決型？共感型？"
  - "建設的な議論？和やかな雑談？"
  - "挑戦的な話題？安全な話題？"
  - "新しい視点？共通の視点？"
  - "質問する？答える？"
  - "教える？教わる？"
  - "人間関係で最も大切にしていることは？"
  - "友達と一番盛り上がる話題って何？"
  - "友達が困ってたら、どう助ける？"
  - "人間関係で「これは苦手だな」ってこと、ある？"
  - "初対面の人と仲良くなるコツ、ある？"
  - "あなたにとって「親友」ってどんな存在？"
