category: "恋愛"
questions:
  - "理想のパートナー像は？"
  - "恋愛で大切にしていることは？"
  - "好きなデートスタイルは？"
  - "恋愛と友情の境界線は？"
  - "一目惚れってある？"
  - "遠距離恋愛についてどう思う？"
  - "恋人とはどのくらいの頻度で連絡を取りたい？"
  - "束縛する？される？どちらも嫌？"
  - "喧嘩した時の仲直り方法は？"
  - "プレゼントを贈るのは好き？"
  - "サプライズは好き？"
  - "恋人の前では素の自分でいられる？"
  - "恋愛と仕事、どちらを優先する？"
  - "結婚についてどう考える？"
  - "子供は欲しい？"
  - "パートナーとの価値観で重要なことは？"
  - "パートナーの趣味が違っても大丈夫？"
  - "恋人の友人との関係はどうあるべき？"
  - "元恋人との関係はどうあるべき？"
  - "告白はどちらからする派？"
  - "恋愛において妥協できることは？"
  - "恋愛において妥協できないことは？"
  - "パートナーに求める条件は？"
  - "年上？年下？同年代？"
  - "恋愛経験は多い方？少ない方？"
  - "恋人と一番「幸せだな」って感じる瞬間は？"
  - "もし恋人と喧嘩しちゃったら、どう仲直りする？"
  - "理想のデート、どんな一日を過ごしたい？"
  - "恋人に「これだけは言われたくない」って言葉ある？"
  - "恋人と二人で無人島に行くなら、何持ってく？"
