category: "学生時代"
questions:
  - "学生時代で一番の思い出は？"
  - "好きだった科目は？"
  - "苦手だった科目は？"
  - "部活動はしていた？"
  - "文化祭や体育祭の思い出は？"
  - "修学旅行の思い出は？"
  - "好きだった先生はいる？"
  - "友達との思い出で印象的なことは？"
  - "勉強方法で工夫していたことは？"
  - "受験の思い出は？"
  - "アルバイトはしていた？"
  - "サークル活動はしていた？"
  - "大学生活で印象的な出来事は？"
  - "一人暮らしの経験は？"
  - "学生時代に熱中していたことは？"
  - "学生時代の恋愛経験は？"
  - "学生時代のファッションは？"
  - "よく行っていた場所は？"
  - "学生時代の食生活は？"
  - "夏休みや長期休暇の過ごし方は？"
  - "卒業旅行の思い出は？"
  - "学生時代に読んでいた本や雑誌は？"
  - "学生時代にハマっていたゲームやアニメは？"
  - "学生時代の自分と今の自分で変わったことは？"
  - "学生時代に戻れるとしたら何をしたい？"
