services:
  dev:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspaces/hitoq:cached    
    ports:
      - "5173:5173"
      - "8000:8000"
    stdin_open: true
    tty: true