"""add_self_introduction_field_to_users

Revision ID: 1b8930c839b6
Revises: e12ea67e6bca
Create Date: 2025-08-05 08:24:39.672009

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b8930c839b6"
down_revision: Union[str, Sequence[str], None] = "e12ea67e6bca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("self_introduction", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "self_introduction")
    # ### end Alembic commands ###
