"""remove_self_introduction_from_users

Revision ID: 1cf365427cbd
Revises: b1199553bafc
Create Date: 2025-08-27 05:48:19.191389

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1cf365427cbd"
down_revision: Union[str, Sequence[str], None] = "b1199553bafc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "self_introduction")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "self_introduction",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
