"""Remove bucket list functionality

Revision ID: 482029939c87
Revises: b5ff33482e52
Create Date: 2025-07-31 06:08:26.433871

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "482029939c87"
down_revision: Union[str, Sequence[str], None] = "b5ff33482e52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bucket_list_items")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bucket_list_items",
        sa.Column(
            "bucket_list_item_id", sa.INTEGER(), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("is_completed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("display_order", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name=op.f("bucket_list_items_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "bucket_list_item_id", name=op.f("bucket_list_items_pkey")
        ),
    )
    # ### end Alembic commands ###
