"""Add visits table and privacy settings

Revision ID: 5b7804721707
Revises: e00cb5f5c5bd
Create Date: 2025-07-28 09:05:12.732589

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b7804721707"
down_revision: Union[str, Sequence[str], None] = "e00cb5f5c5bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "visits",
        sa.Column("visit_id", sa.Integer(), nullable=False),
        sa.Column("visitor_user_id", sa.String(), nullable=True),
        sa.Column("visited_user_id", sa.String(), nullable=False),
        sa.Column("is_anonymous", sa.Boolean(), nullable=False),
        sa.Column(
            "visited_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["visited_user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["visitor_user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("visit_id"),
    )
    op.add_column(
        "users",
        sa.Column(
            "visits_visible",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "visits_visible")
    op.drop_table("visits")
    # ### end Alembic commands ###
