"""add_parent_message_id_for_replies

Revision ID: 719c718fd264
Revises: 78c914bb225d
Create Date: 2025-08-03 10:16:06.802720

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "719c718fd264"
down_revision: Union[str, Sequence[str], None] = "78c914bb225d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages", sa.Column("parent_message_id", sa.String(), nullable=True)
    )
    op.create_foreign_key(
        None, "messages", "messages", ["parent_message_id"], ["message_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_column("messages", "parent_message_id")
    # ### end Alembic commands ###
