"""add_notification_level_to_users

Revision ID: 78c914bb225d
Revises: e7275d6f281e
Create Date: 2025-08-03 09:28:07.155290

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78c914bb225d"
down_revision: Union[str, Sequence[str], None] = "e7275d6f281e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first
    notification_level_enum = sa.Enum(
        "none", "important", "all", name="notificationlevelenum"
    )
    notification_level_enum.create(op.get_bind())

    # Add the column with the ENUM type
    op.add_column(
        "users",
        sa.Column(
            "notification_level",
            notification_level_enum,
            nullable=False,
            server_default="all",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "notification_level")

    # Drop the ENUM type
    notification_level_enum = sa.Enum(
        "none", "important", "all", name="notificationlevelenum"
    )
    notification_level_enum.drop(op.get_bind())
    # ### end Alembic commands ###
