"""add_template_id_column_to_questions

Revision ID: b5ff33482e52
Revises: dddb810aab47
Create Date: 2025-07-28 13:33:29.720140

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5ff33482e52"
down_revision: Union[str, Sequence[str], None] = "dddb810aab47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # まずnullableでカラムを追加
    op.add_column("questions", sa.Column("template_id", sa.String(), nullable=True))

    # 既存データにtemplate_idを設定（カテゴリ名をtemplate_idとして使用）
    connection = op.get_bind()
    connection.execute(
        sa.text("""
        UPDATE questions 
        SET template_id = category 
        WHERE template_id IS NULL
    """)
    )

    # NOT NULL制約を追加
    op.alter_column("questions", "template_id", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "template_id")
    # ### end Alembic commands ###
