"""add user blocks and reports tables

Revision ID: d66efaf79efc
Revises: 1b8930c839b6
Create Date: 2025-08-06 05:00:57.329721

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d66efaf79efc"
down_revision: Union[str, Sequence[str], None] = "1b8930c839b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_blocks",
        sa.Column("block_id", sa.Uuid(), nullable=False),
        sa.Column("blocker_user_id", sa.String(), nullable=False),
        sa.Column("blocked_user_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["blocked_user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["blocker_user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("block_id"),
    )
    op.create_table(
        "user_reports",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("reporter_user_id", sa.String(), nullable=False),
        sa.Column("reported_user_id", sa.String(), nullable=False),
        sa.Column(
            "report_type",
            sa.Enum(
                "spam",
                "harassment",
                "inappropriate_content",
                "other",
                name="reporttypeenum",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "reviewing", "resolved", "dismissed", name="reportstatusenum"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["reported_user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["reporter_user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("report_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_reports")
    op.drop_table("user_blocks")
    # ### end Alembic commands ###
