"""add_template_id_to_questions

Revision ID: dddb810aab47
Revises: 5b7804721707
Create Date: 2025-07-28 11:51:26.109125

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "dddb810aab47"
down_revision: Union[str, Sequence[str], None] = "5b7804721707"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
