"""update_questions_to_flat_category_structure

Revision ID: e7275d6f281e
Revises: f55fcfe2b539
Create Date: 2025-08-01 15:04:06.266976

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7275d6f281e"
down_revision: Union[str, Sequence[str], None] = "f55fcfe2b539"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("category_id", sa.String(), nullable=False))
    op.drop_column("questions", "category")
    op.drop_column("questions", "template_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column("template_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "questions",
        sa.Column(
            "category",
            postgresql.ENUM(
                "self_introduction",
                "values",
                "otaku",
                "misc",
                name="questioncategoryenum",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("questions", "category_id")
    # ### end Alembic commands ###
