"""Add messages functionality

Revision ID: f55fcfe2b539
Revises: 482029939c87
Create Date: 2025-07-31 07:08:24.530801

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f55fcfe2b539"
down_revision: Union[str, Sequence[str], None] = "482029939c87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("from_user_id", sa.String(), nullable=False),
        sa.Column("to_user_id", sa.String(), nullable=False),
        sa.Column(
            "message_type",
            sa.Enum(
                "question", "comment", "request", "reaction", name="messagetypeenum"
            ),
            nullable=False,
        ),
        sa.Column("content", sa.String(length=500), nullable=False),
        sa.Column("reference_answer_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("unread", "read", "replied", name="messagestatusenum"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["reference_answer_id"],
            ["answers.answer_id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    # ### end Alembic commands ###
