"""Add message and answer likes tables

Revision ID: fd6b6177424f
Revises: 69f269808e64
Create Date: 2025-08-27 15:52:30.336374

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd6b6177424f"
down_revision: Union[str, Sequence[str], None] = "69f269808e64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answer_likes",
        sa.Column("like_id", sa.Uuid(), nullable=False),
        sa.Column("answer_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answers.answer_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("like_id"),
        sa.UniqueConstraint("answer_id", "user_id", name="uq_answer_user_like"),
        comment="QA回答のいいね機能",
    )
    op.create_table(
        "message_likes",
        sa.Column("like_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.message_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("like_id"),
        sa.UniqueConstraint("message_id", "user_id", name="uq_message_user_like"),
        comment="メッセージのいいね機能",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_likes")
    op.drop_table("answer_likes")
    # ### end Alembic commands ###
