versions:
  profile_labels: v1.1
  question_templates: v1.0
migrations:
  profile_labels:
    - version: v1.0
      date: "2025-01-30"
      description: Initial profile labels configuration
      labels:
        - 趣味・今ハマっていること
        - 好きなコンテンツ
        - 好きな食べ物
        - 得意なこと・特技
        - 実は〇〇なんです
        - 子供の頃の夢
        - 座右の銘
        - もし１つだけ願いが叶うなら？
      mappings: {}
    - version: v1.1
      date: "2025-07-30"
      description: Updated to version v1.1
      labels:
        - 趣味・今ハマっていること
        - 好きなコンテンツ
        - 好きな食べ物
        - 得意なこと・特技
        - 実は〇〇なんです
        - 子供の頃の夢
        - 座右の銘
        - もし１つだけ願いが叶うなら？
      mappings: {}
