name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read

    env:
      # Render API Key for deployment
      TF_VAR_render_api_key: ${{ secrets.RENDER_API_KEY }}
      TF_VAR_render_owner_id: ${{ secrets.RENDER_OWNER_ID }}

      # Database Configuration
      TF_VAR_db_host: ${{ secrets.DB_HOST }}
      TF_VAR_db_user: ${{ secrets.DB_USER }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_db_name: ${{ vars.DB_NAME }}
      TF_VAR_db_port: ${{ vars.DB_PORT }}

      # Application Security
      TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
      TF_VAR_session_secret_key: ${{ secrets.SESSION_SECRET_KEY }}

      # Twitter OAuth Configuration
      TF_VAR_twitter_client_id: ${{ secrets.TWITTER_CLIENT_ID }}
      TF_VAR_twitter_client_secret: ${{ secrets.TWITTER_CLIENT_SECRET }}
      TF_VAR_twitter_redirect_uri: ${{ vars.TWITTER_REDIRECT_URI }}

      # Frontend Configuration
      TF_VAR_frontend_urls: ${{ vars.FRONTEND_URLS }}
      TF_VAR_public_api_base_url: ${{ vars.PUBLIC_API_BASE_URL }}

      # Environment Settings
      TF_VAR_environment: ${{ vars.ENVIRONMENT }}
      TF_VAR_cookie_secure: ${{ vars.COOKIE_SECURE }}
      TF_VAR_log_level: ${{ vars.LOG_LEVEL }}

      # Monitoring and Logging
      TF_VAR_sentry_dsn: ${{ secrets.SENTRY_DSN }}
      TF_VAR_public_sentry_dsn: ${{ vars.PUBLIC_SENTRY_DSN }}
      TF_VAR_public_environment: ${{ vars.PUBLIC_ENVIRONMENT }}

      # CORS Settings
      TF_VAR_cors_allow_methods: ${{ vars.CORS_ALLOW_METHODS }}
      TF_VAR_cors_allow_headers: ${{ vars.CORS_ALLOW_HEADERS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x.x
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Check Terraform Version
        run: terraform version

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -detailed-exitcode
        continue-on-error: true

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
