name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production # Optional: for environment protection rules and secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Frontend Docker image
        working-directory: ./frontend
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/hitoq-frontend
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Build and push Backend Docker image
        working-directory: ./backend
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/hitoq-backend
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x.x # Specify your Terraform version

      - name: Terraform Init
        working-directory: ./terraform # Assuming your Terraform files are in this directory
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve # -auto-approve is for CI/CD, be careful with this in production
        env:
          # Add any necessary cloud provider credentials here as GitHub Secrets
          # e.g., AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #       AWS_REGION: your-aws-region
          # Pass image tags to Terraform if needed
          TF_VAR_frontend_image: ghcr.io/${{ github.repository_owner }}/hitoq-frontend:${{ github.sha }}
          TF_VAR_backend_image: ghcr.io/${{ github.repository_owner }}/hitoq-backend:${{ github.sha }}
